// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OrderManagementMVC.Models
{
    public partial class LabelsModel
    {
        public int LabelId { get; set; }
        public string LabelName { get; set; }
        public double Heigth { get; set; }
        public double Width { get; set; }
    }
}