// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OrderManagementMVC.Models
{
    public partial class OrdersModel
    {
        public int OrderNumber { get; set; }
        public string Client { get; set; }
        public string DocumentName { get; set; }
        public string DocumentFormat { get; set; }
        public string EnvelopeType { get; set; }
        public int Quantity { get; set; }
        public int PagesOnEnvelope { get; set; }
        public string LabelType { get; set; }
        public string OrderStatus { get; set; }
        public int Completed { get; set; }
        public DateTime DateInSystem { get; set; }
        public DateTime? DateFinished { get; set; }
        public DateTime? DateInProduction { get; set; }
        public bool? HasCustomSort { get; set; }
        public string CustomSortFile { get; set; }
        public string CustomSortField { get; set; }
    }
}