// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OrderManagementMVC.Models
{
    public partial class OrderTraceModel
    {
        public int Id { get; set; }
        public string IdBoxNumber { get; set; }
        public DateTime? DateOut { get; set; }
        public string MachineId { get; set; }

        public virtual OrderLabelsModel IdBoxNumberNavigation { get; set; }
    }
}